apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80           # External Service port
      targetPort: 5000   # Internal container port
  type: NodePort         # ClusterIP for internal, NodePort for fixed port, LoadBalancer for cloud
