apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api-deployment
  labels:
    app: ml-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
        - name: ml-api-container
          image: muhdshahan/ml-api:latest  # 🖊️ Replace with your image
          ports:
            - containerPort: 5000
          env:
            - name: MODEL_PATH
              value: "/models/model.joblib"
