apiVersion: v1
kind: Service
metadata:
  name: ml-api-service
spec:
  type: NodePort  # ClusterIP for internal, NodePort for fixed port, LoadBalancer for cloud
  selector:
    app: ml-api
  ports:
    - protocol: TCP
      port: 80           # External Service port
      targetPort: 5000   # Internal container port
