name: MLOps Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Train, Evaluate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Train model
      run: python src/train.py

    - name: Evaluate model
      run: python src/evaluate.py

    - name: Run API test with pytest
      run: PYTHONPATH=. pytest test/test_app.py

  build_and_deploy:
    name: Build and Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: build_and_test  # Only run if build_and_test suceed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with: 
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app-cicd-project:latest

      